name: Vinted Nike Alert

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le projet
        uses: actions/checkout@v4

      - name: Installer Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Installer les dépendances
        run: npm install

      - name: Installer Chromium
        run: npx playwright install --with-deps chromium

      - name: Lancer le radar Vinted
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          MAX_PRICE_EUR: 25
        run: npm start
